# begin

In [83]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [84]:
sess = tf.Session()

In [27]:
my_tensor = tf.zeros([1,20])

In [28]:
print(my_tensor)

Tensor("zeros_1:0", shape=(1, 20), dtype=float32)


In [29]:
sess.run(my_tensor)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [40]:
my_var = tf.Variable(tf.zeros([1,20]), name = 'my_var')

In [41]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [31]:
row_dim = 2
col_dim = 3

In [32]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

In [33]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
sess.run(zero_var)
print(sess.run(ones_var))

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
type(zero_similar)

tensorflow.python.ops.variables.Variable

In [36]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


In [37]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


In [38]:
# Linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=10)) # Generates [0.0, 0.5, 1.0] includes the end

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=2)) # Generates [6, 9, 12] doesn't include the end

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[0.         0.11111111 0.22222222 0.33333334 0.44444445 0.5555556
 0.6666667  0.7777778  0.8888889  1.        ]
[ 6  8 10 12 14]


# Write log -> TensorBoard

In [53]:
# Reset graph
#ops.reset_default_graph()

# Start a graph session
#sess = tf.Session()

# Create variable
#my_var = tf.Variable(tf.zeros([1,20]))

# Add summaries to tensorboard
merged = tf.summary.merge_all()

# Initialize graph writer:
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# Initialize operation
initialize_op = tf.global_variables_initializer()

# Run initialization of variable
sess.run(initialize_op)

# 1.3

In [51]:
x = tf.placeholder(tf.float32, shape=[4, 4])

In [52]:
# Input data to placeholder, note that 'rand_array' and 'x' are the same shape.
rand_array = np.random.rand(4, 4)

# Create a Tensor to perform an operation (here, y will be equal to x, a 4x4 matrix)
y = tf.identity(x)

# Print the output, feeding the value of x into the computational graph
print(sess.run(y, feed_dict={x: rand_array}))

[[0.69260395 0.4870417  0.27914137 0.7459464 ]
 [0.9847481  0.6134899  0.49173173 0.8623747 ]
 [0.42688662 0.43829829 0.35256913 0.96668464]
 [0.96229076 0.2549821  0.56301844 0.29536536]]


# 1.4

In [54]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix)) #单位矩阵

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
A = tf.truncated_normal([2,3]) #截断正太分布
print(sess.run(A))

[[-0.419743   -0.9930827  -1.1056675 ]
 [-0.09077056  0.9308896   0.2911218 ]]


In [56]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [57]:
type(B)

tensorflow.python.framework.ops.Tensor

In [75]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.738361   0.74277055]
 [0.44631004 0.6096238 ]
 [0.91492724 0.7440748 ]]


In [72]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]), dtype = float)
print(D)

Tensor("Const_4:0", shape=(3, 3), dtype=float32)


In [61]:
print(sess.run(A+B))
print(sess.run(B-B))

[[5.8286915 4.66452   4.407404 ]
 [4.8653636 6.143059  5.8007307]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
print(sess.run(tf.matmul( D,tf.matrix_inverse(D))))

[[1.0000000e+00 2.9802322e-08 1.4901161e-08]
 [1.4901161e-07 1.0000000e+00 1.2479722e-07]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]


In [65]:
print(sess.run(tf.transpose(B))) # 转置

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [76]:
print(sess.run(tf.matrix_determinant(D))) #行列式

-38.0


In [77]:
print(sess.run(tf.matrix_inverse(D))) #逆矩阵

[[-0.50000006 -0.5        -0.50000006]
 [ 0.15789475  0.05263158  0.21052633]
 [ 0.39473686  0.13157895  0.0263158 ]]


In [81]:
print(sess.run(tf.cholesky(identity_matrix))) #https://zh.wikipedia.org/wiki/Cholesky%E5%88%86%E8%A7%A3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [82]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.659076    -0.22750695   2.886583  ]
[[-0.21749546 -0.6325011  -0.74339646]
 [-0.84526515 -0.25879988  0.46749276]
 [ 0.48808062 -0.7300446   0.4783433 ]]


# 1.5 Operations

In [86]:
print(sess.run(tf.div(3,4)))
print(sess.run(tf.div(3.0,4)))
print(sess.run(tf.truediv(3,4)))
print(sess.run(tf.floordiv(3.0,4.0)))

0
0.75
0.75
0.0


In [87]:
print(sess.run(tf.mod(22.0,5.0)))

2.0


In [90]:
print(sess.run(tf.cross([1.,2.,3.],[0.,1.,0.])))

[-3.  0.  1.]


In [91]:
print(sess.run(tf.sin(3.1416)))
print(sess.run(tf.cos(3.1416)))
print(sess.run(tf.div(tf.sin(3.1416/4.), tf.cos(3.1416/4.))))

-7.2399803e-06
-1.0
1.0000036


In [96]:
test_nums = range(15)

def custom_polynomial(x_val):
    # Return 3x^2 - x + 10
    return(tf.subtract(3 * tf.square(x_val), x_val) + 10)

print(sess.run(custom_polynomial(11)))

AttributeError: module 'tensorflow' has no attribute 'sub'

In [94]:
expected_output = [3*x*x-x+10 for x in test_nums]
print(expected_output)

[10, 12, 20, 34, 54, 80, 112, 150, 194, 244, 300, 362, 430, 504, 584]


In [95]:
for num in test_nums:
    print(sess.run(custom_polynomial(num)))

10
12
20
34
54
80
112
150
194
244
300
362
430
504
584
